add deserialize_file()
JuliaComputing/OpenAPI.jl pull request #51
Opened 2023-07-28 14:17 UTC by NeroBlackstone

Related issue #46.

I did not write test code, since I don't know how to build a download server #50 

But codes should work, I test it on another project.

![image](https://github.com/JuliaComputing/OpenAPI.jl/assets/17470335/3c33325d-4786-40a0-9446-071a724abc9f)

2023-07-29 10:29 UTC, tanmaykm requested changes

2023-07-29 10:29 UTC, tanmaykm commented on src/client.jl
> +    file_name = if length(rename_file) > 0
```suggestion
    file_name = if !isempty(rename_file)
```

2023-07-29 10:29 UTC, tanmaykm commented on src/client.jl
> +    elseif length(content_disposition_str) > 0
```suggestion
    elseif !isempty(content_disposition_str)
```

2023-07-29 10:29 UTC, tanmaykm commented on src/client.jl
> +    if !(isfile(file_path)&&!overwrite)
Not sure if we should accept an option to not `overwrite`. There may be more than one way the method may be expected to behave when file already exists and overwrite is false. Same goes for the folder name.

I feel it is best left for the caller to pass the exact folder and file names, and let the method always replace the file.

2023-07-29 15:31 UTC, NeroBlackstone commented
I think I have finished what you suggested.
btw, Shall we add a `Configuration` struct to save server/client configuration like [here](https://github.com/Kaggle/kaggle-api/blob/75dfa27d3c2886ea46e4d0c6bfcc0cc322af554b/kaggle/configuration.py#L56)?

And `deserialize_file()` uses the default download location from this object.
So we can change all default download locations in one place, instead manually passing argument again and again when using `deserialize_file()`.

2023-07-31 15:12 UTC, tanmaykm approved these changes

2023-07-31 15:14 UTC, tanmaykm commented
I think the configuration struct is something specific that a client application needs to maintain, it should not be part of the openapi package.

Merging this now, and I'll attempt writing some test cases for it subsequently.

2023-07-31 15:14 UTC, merged

2023-07-31 16:09 UTC, NeroBlackstone commented
Thanks, after testing these codes and adding docs, please make a new release. 
I'll close #46 if everything is okay.